DROP TABLE IF EXISTS url_checks;
DROP TABLE IF EXISTS urls;

CREATE TABLE urls (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE url_checks (
    id BIGSERIAL PRIMARY KEY,
    url_id BIGSERIAL REFERENCES urls(id) NOT NULL,
    status_code INT,
    title VARCHAR(255),
    h1 VARCHAR(255),
    description text,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);